### ISSUE TITLE
TX for SUP

### ISSUE THREAD

**Issue by RudiZhang** [pierr3/VectorAudio#76]
It is unable to use TX if I'm online as a SUP. Would that be possible to fix in the future?

**Comment by pierr3** [comment]
This should already be the case but I will verify, fix will be provided in the next release if not!

**Comment by pierr3** [comment]
Confirmed that this is fixed in the code and will be available in the next release

**Comment by RudiZhang** [comment]
![image](https://github.com/pierr3/VectorAudio/assets/40914896/526c39c0-b8c6-453c-a7ab-0c20e45178af)

@pierr3 still unable to use TX

**Comment by pierr3** [comment]
Thank you, I think there may be a slight difference in the API for sups that I missed. Apologies, will review.

**Comment by pierr3** [comment]
I fixed that one, as for the crash I am not sure. I will try to push a new release but it won't be so soon.
